name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Show package.json (for Vite debug)
        working-directory: ./app
        run: cat package.json

      - name: Install dependencies
        working-directory: ./app
        run: npm install

      - name: Debug API Key before build
        run: echo "key = $VITE_TMDB_API_KEY"
        env:
          VITE_TMDB_API_KEY: ${{ secrets.VITE_TMDB_API_KEY }}

      - name: Build project with Vite
        working-directory: ./app
        run: npm run build
        env:
          VITE_TMDB_API_KEY: ${{ secrets.VITE_TMDB_API_KEY }}

      - name: Check if dist/ directory exists
        working-directory: ./app
        run: ls -al dist

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy dist/ to S3
        working-directory: ./app
        run: aws s3 sync dist/ s3://cinequest --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
          --distribution-id EA9PU6C3T0BST \
          --paths "/*"
