name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Afficher le contenu de package.json (debug vite)
        working-directory: ./app
        run: cat package.json

      - name: Installer les dépendances
        working-directory: ./app
        run: npm install

      - name: Build avec Vite
        working-directory: ./app
        run: npm run build

      - name: Vérifier que le dossier dist existe
        working-directory: ./app
        run: ls -al dist

      - name: Configurer les credentials AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Déployer sur S3 depuis dist (Vite)
        working-directory: ./app
        run: aws s3 sync dist/ s3://cinequest --acl public-read --delete
